let times= [
  { nome: "Cachichi", cidade: "Santo André", bairro: "Campestre", ranking: 1843.73, forca: 0 },
  { nome: "Quetos",cidade: "Santo André", bairro: "Vila Alzira", ranking: 1512.82, forca: 0 },
  { nome: "Dorflex",cidade: "Santo André", bairro: "Jardim Bela Vista", ranking: 1553.23, forca: 0 },
  { nome: "Boston",cidade: "Santo André", bairro: "Utinga", ranking: 1444.44,forca: 0},
  { nome: "Santito", cidade: "São Bernardo", bairro: "Batistini", ranking: 596.062, forca: 0 },
  { nome: "Rufus", cidade: "São Bernardo", bairro: "Anchieta", ranking: 981.223, forca: 0 },
  { nome: "Toquio", cidade: "São Bernardo", bairro: "Baeta Neves", ranking: 1.117523, forca: 0 },
  { nome: "Fúria", cidade: "São Bernardo", bairro: "Ferrazópolis", ranking: 856.325, forca: 0 },
  { nome: "Trovões", cidade: "Diadema", bairro: "Casa Grande", ranking: 1.162924, forca: 0 },
  { nome: "Havai", cidade: "Diadema", bairro: "Piraporinha", ranking: 951.131, forca: 0 },
  { nome: "Onduras", cidade: "Diadema", bairro: "Eldorado", ranking: 1.061821, forca: 0 },
  { nome: "Fenix", cidade: "Diadema", bairro: "Canhema", ranking: 786.600, forca: 0 },
  { nome: "Titãs", cidade: "São Caetano do Sul", bairro: "Oswaldo Cruz", ranking: 1.068956, forca: 0 },
  { nome: "Spoleto", cidade: "São Caetano do Sul", bairro: "Fundação", ranking: 864.417, forca: 0 },
  { nome: "Potato", cidade: "São Caetano do Sul", bairro: "Boa Vista", ranking: 834.531, forca: 0 },
  { nome: "Tarja", cidade: "São Caetano do Sul", bairro: "Barcelona", ranking: 682.039, forca: 0 }
];
